apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - ../../base/namespace.yaml
  - ../../base/deps.yaml
  - ../../base/app-deployment.yaml
  - ../../base/app-service-nodeport.yaml
  - ../../base/servicemonitor.yaml

commonLabels:
  environment: local

images:
  - name: danimoreira5150/user-service
    newTag: latest
