apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: ecommerce
  labels:
    app: user-service
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: user-service
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
